### ISSUE TITLE
关于虾米cookie的pnm_cku822

### ISSUE THREAD

**Issue by creamidea** [isombyt/XiaQian#1]
请isombyt原谅我问一个愚蠢的问题：这个XiaQian还能使用吗？（刚刚在本地测试了一下，但是要等到明天才出结果，>_<，但是现在迫不及待地想知道结果，所以就来问问了。）

我自己写了一个python脚本，但是死活签不了，后来我发现貌似需要传入一个pnm_chu822这个cookie的值，但是这个值是js在页面渲染时生成的，cookieJar拿不到这个值（还是我打开的姿势不对？）不知道isombyt你是如何解决这个问题的？还是我的思路不对，愿isombyt能赐予我「力量」解决这个问题。

以上です。

乾杯！( ^_^)／□☆□＼(^-^ )

**Comment by isombyt** [comment]
我不清楚你说的渲染的时候生成是什么时候。如果是在页面返回里面的话，可以先请求一次页面，用re或者lxml取出来。如果是aiax获取的话，可以用chrome看一下网络请求，看看是哪个请求里面包含这个值，然后再自己去获取一次。

**Comment by creamidea** [comment]
啊呀，果然是我错了。  >_<

今天我发现原来pnm_chu822这个不是关键的，关键的是t_sign_auth（GET /index/home HTTP/1.1）. 于是虾米签到需要的是:
- _unsign_token  
- _xiamitoken  
- member_auth 
- user
- t_sign_auth （貌似这个就是你已经签到的次数）

果然可以了。多谢isombyt的提醒。

关于我说的pnm_cku822昨天忘记具体说明了，sorry。截图如下，这个是在首页中出现的：
![screenshot_052614_065549_am](https://cloud.githubusercontent.com/assets/1274730/3078162/b83c5dd4-e45f-11e3-8016-3e994f03cc1e.jpg)

（如果图片君消失了，请戳这里：https://cloud.githubusercontent.com/assets/1274730/3078162/b83c5dd4-e45f-11e3-8016-3e994f03cc1e.jpg）

那对于这种用js生成的cookie有什么好办法吗？（昨天我尝试用PyExecJS来运行这段js代码，但是失败了，首页中应该还有其他地方运行计算了pnm_cku822，有空的时候在具体研究一下）

以上。

**Comment by isombyt** [comment]
没看到图...

**Comment by creamidea** [comment]
![screenshot_052614_115730_am](https://cloud.githubusercontent.com/assets/1274730/3079027/dcfbf6e6-e489-11e3-8ea1-84d24fc992c8.jpg)

效果如下：
貌似我在comment加入一个这个<body />后面的就消失了，有空你可以感受一下：）

**Comment by amazingfate** [comment]
在vps上部署虾签有两三个月了，目前遇到两次虾米签到突然中断的情况，Ctrl页面能正常访问，进程中也有WebManager.py，可是签到还是断了，必须重启服务，不知有没有人遇到这个问题

**Comment by isombyt** [comment]
确实是会这样，所以更好的解决方案是用cron定时任务而不是跑一个协程跑死循环来签到..

**Comment by creamidea** [comment]
目前来看没有什么问题了，暂时关闭这个issue
